# Generated by Django 5.0.4 on 2026-01-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('building_sqft', models.IntegerField(null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('stories', models.IntegerField(null=True)),
                ('property_type', models.CharField(max_length=100)),
                ('garage', models.CharField(blank=True, max_length=50, null=True)),
                ('land_size', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('lot_sqft', models.IntegerField(null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('tax_status', models.CharField(default='Unknown', max_length=50)),
                ('delinquent', models.BooleanField(default=False)),
                ('tax_year', models.IntegerField(null=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraiser_url', models.URLField(blank=True, null=True)),
                ('tax_collector_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
