# Generated by Django 4.2.11 on 2024-05-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('image_of_property', models.URLField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('stories', models.IntegerField(null=True)),
                ('home_size', models.IntegerField(null=True)),
                ('lot_size', models.IntegerField(null=True)),
                ('property_type', models.CharField(max_length=100)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('garage', models.CharField(max_length=50, null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('time_on_market', models.IntegerField(null=True)),
                ('estimated_monthly_payment', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('home_insurance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('hoa_fees', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mortgage_insurance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('property_tax', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
