# Generated by Django 5.0.4 on 2026-01-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
