# Generated by Django 5.0.4 on 2026-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraper', '0002_add_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='delinquent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='market_value',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='tax_status',
            field=models.CharField(db_index=True, default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='year_built',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='zip_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['city', 'property_type'], name='idx_city_proptype'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['city', 'zip_code'], name='idx_city_zip'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['city', 'market_value'], name='idx_city_value'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['property_type', 'market_value'], name='idx_proptype_value'),
        ),
    ]
