# Generated by Django 5.0.4 on 2026-04-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraper', '0003_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='address',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['city', 'property_type', 'market_value'], name='idx_city_type_value'),
        ),
    ]
