# Generated by Django 4.2.11 on 2024-05-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data_type', models.CharField(default='text', max_length=50)),
                ('help_text', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('listing_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
