# Generated by Django 5.2.14 on 2026-09-30 21:04

from django.db import migrations, models

# On PostgreSQL, Django gives every indexed or unique CharField a second
# varchar_pattern_ops "_like" index for LIKE 'prefix%' lookups. The AlterField
# operations below drop the ones on address, city, property_type and
# tax_status. parcel_id and zip_code keep their plain indexes, but nothing does
# prefix matching on them, so their _like indexes only cost storage.
LIKE_INDEX_FIELDS = ('parcel_id', 'zip_code')


def drop_like_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    model = apps.get_model('WebScraper', 'PropertyListing')
    for field_name in LIKE_INDEX_FIELDS:
        field = model._meta.get_field(field_name)
        name = schema_editor._create_index_name(model._meta.db_table, [field.column], suffix='_like')
        schema_editor.execute(schema_editor._delete_index_sql(model, name))  # DROP INDEX IF EXISTS


def restore_like_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    model = apps.get_model('WebScraper', 'PropertyListing')
    for field_name in LIKE_INDEX_FIELDS:
        schema_editor.execute(schema_editor._create_like_index_sql(model, model._meta.get_field(field_name)))


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0006_keep_only_pcpao_photos'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertylisting',
            name='idx_city_proptype',
        ),
        migrations.RemoveIndex(
            model_name='propertylisting',
            name='idx_city_zip',
        ),
        migrations.RemoveIndex(
            model_name='propertylisting',
            name='idx_city_value',
        ),
        migrations.RemoveIndex(
            model_name='propertylisting',
            name='idx_proptype_value',
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='delinquent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='tax_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.RunPython(drop_like_indexes, restore_like_indexes),
    ]
