# Generated by Django 5.2.14 on 2026-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0007_drop_unused_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='contamination',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='evac_zone',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='frontage',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='historic_landmark',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='homestead_cap',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='living_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='millage_rate',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='neighborhood_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='roll_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='sales_comp_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='seawall',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='special_assessment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='subsidence',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='tax_district',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='views',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='waterfront',
            field=models.BooleanField(null=True),
        ),
    ]
