# Generated by Django 5.2.14 on 2026-09-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0008_add_pcpao_tax_and_risk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='est_tax_current',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='est_tax_homestead',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='est_tax_no_homestead',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TaxDistrictMillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=8)),
                ('tax_year', models.IntegerField()),
                ('rate_description', models.CharField(max_length=32)),
                ('total_mills', models.DecimalField(decimal_places=4, max_digits=7)),
                ('school_mills', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('district_code', 'tax_year'), name='uniq_millage_district_year')
                ],
            },
        ),
    ]
