# Generated by Django 5.2.14 on 2026-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0009_tax_estimates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['address'], name='idx_address_prefix', opclasses=['varchar_pattern_ops']),
        ),
    ]
