# Generated by Django 5.2.14 on 2026-10-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0010_address_prefix_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('as_of', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
