# Generated by Django 5.2.14 on 2026-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0011_mortgage_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=50)),
                ('sale_date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['neighborhood_code'], name='idx_neighborhood'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('parcel_id', 'sale_date'), name='uniq_sale_parcel_date'),
        ),
    ]
