# Generated by Django 5.2.14 on 2026-10-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0012_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='hvac_permit_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='roof_permit_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
