# Generated by Django 5.2.14 on 2026-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebScraper', '0013_permit_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFloodHistory',
            fields=[
                ('zip_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('claim_count', models.IntegerField()),
                ('recent_claim_count', models.IntegerField()),
                ('median_paid', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='flood_zone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='static_bfe',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
